// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/config/filter/network/trpc_proxy/v3/trpc_proxy.proto

package envoy_config_filter_network_trpc_proxy_v3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on TrpcProxy with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *TrpcProxy) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetAccessLog() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TrpcProxyValidationError{
					field:  fmt.Sprintf("AccessLog[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for StatPrefix

	switch m.RouteSpecifier.(type) {

	case *TrpcProxy_Rds:

		if v, ok := interface{}(m.GetRds()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TrpcProxyValidationError{
					field:  "Rds",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *TrpcProxy_RouteConfig:

		if v, ok := interface{}(m.GetRouteConfig()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TrpcProxyValidationError{
					field:  "RouteConfig",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		return TrpcProxyValidationError{
			field:  "RouteSpecifier",
			reason: "value is required",
		}

	}

	return nil
}

// TrpcProxyValidationError is the validation error returned by
// TrpcProxy.Validate if the designated constraints aren't met.
type TrpcProxyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrpcProxyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrpcProxyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrpcProxyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrpcProxyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrpcProxyValidationError) ErrorName() string { return "TrpcProxyValidationError" }

// Error satisfies the builtin error interface
func (e TrpcProxyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrpcProxy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrpcProxyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrpcProxyValidationError{}
